/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#4c4546",
        "on-error": "#ffffff",
        "on-primary-container": "#848484",
        "secondary-fixed": "#e2e2e4",
        secondary: "#5d5e60",
        "inverse-on-surface": "#f0f1f1",
        "secondary-fixed-dim": "#c6c6c8",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-primary": "#c6c6c6",
        "surface-bright": "#f9f9f9",
        "on-primary": "#ffffff",
        primary: "#000000",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#474747",
        "error-container": "#ffdad6",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary-container": "#838388",
        background: "#f9f9f9",
        "on-secondary-container": "#616365",
        "surface-container-low": "#f3f3f4",
        "tertiary-fixed-dim": "#c7c6cb",
        "on-surface": "#1a1c1c",
        "tertiary-container": "#1a1b1f",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#1a1b1f",
        "outline-variant": "#cfc4c5",
        outline: "#7e7576",
        "on-primary-fixed": "#1b1b1b",
        tertiary: "#000000",
        "tertiary-fixed": "#e3e2e7",
        surface: "#f9f9f9",
        error: "#ba1a1a",
        "secondary-container": "#dfdfe1",
        "surface-container": "#eeeeee",
        "surface-tint": "#5e5e5e",
        "on-secondary-fixed-variant": "#454749",
        "surface-variant": "#e2e2e2",
        "primary-fixed": "#e2e2e2",
        "on-background": "#1a1c1c",
      },
      fontFamily: {
        manrope: ["Manrope", "sans-serif"],
      },
      spacing: {
        sm: "12px",
        xs: "4px",
        "container-max": "1280px",
        xl: "80px",
        md: "24px",
        lg: "48px",
        gutter: "24px",
        base: "8px",
      },
    },
  },
  plugins: [],
};
